{% set name = "opentelemetry-instrumentation-psycopg2" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-psycopg2-{{ version }}.tar.gz
  sha256: 8eca0856076b12a15ab5dc3a9a62dc2ca7e5e9021a7e33e24d12274aad338d0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-instrumentation-dbapi ==0.26b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - psycopg2 >=2.7.3.1
    # - opentelemetry-test ==0.24b0
    # - psycopg2 >=2.7.3.1
    # - opentelemetry-test ==0.25b0
    # - psycopg2 >=2.7.3.1
    # - opentelemetry-test ==0.25b2
    # - psycopg2 >=2.7.3.1
    # - opentelemetry-test-utils ==0.26b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-psycopg2
  summary: OpenTelemetry psycopg2 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
